### ISSUE TITLE
C# EntryPointNotFoundException on yolo_cpp_dll

### ISSUE THREAD

**Issue by tinohager** [AlexeyAB/darknet#1072]
Hello

I try to use the yolo_cpp_dll from a c# project but i don't can send any request. It always fails with an EntryPointNotFoundException.

![2018-06-22 20_38_48-alturos yolo debugging - microsoft visual studio](https://user-images.githubusercontent.com/8215186/41793460-6e9dd886-765c-11e8-8233-c5d991047950.png)

I have found this example code https://github.com/rodrigojbp/YoloCSharp/blob/master/YoloNOGPUCSharpClient/YoloBridge.cs but its also not work.

    public struct image_t
    {
        int h;
        int w;
        int c;
        //float[] data;
    };

    [DllImport("yolo_cpp_dll")]
    public static extern image_t load_image(string fileName);

**Similar Issues**

- [118 - use yolo_cpp_dll.dll in c# project](https://github.com/AlexeyAB/darknet/issues/118)
- [187 - Crashes when trying to use yolo_dll.dll in C#](https://github.com/AlexeyAB/darknet/issues/187)

Current workaround

We have this project [Alturos.Yolo](https://github.com/AlturosDestinations/Alturos.Yolo) but we don't have gpu support. I would like to use your project dll.

**Comment by tinohager** [comment]
We have this project [Alturos.Yolo](https://github.com/AlturosDestinations/Alturos.Yolo) but we don't have gpu support. I would like to use your project dll.

**Comment by tinohager** [comment]
I have found a solution i don't know it is perfect but it's works. One limitation is available only one bbox_t return. Compiled with opencv 3.4.0 (opencv_world340.dll) and cuda 9.2 (cudnn64_7.dll)
[yolo_cpp_dll.zip](https://github.com/AlexeyAB/darknet/files/2129179/yolo_cpp_dll.zip)

**C# YoloWrapper**

    public class YoloWrapper : IDisposable
    {
        [DllImport("yolo_cpp_dll.dll")]
        public static extern int init(string configurationFilename, string weightsFilename, int gpu);

        [DllImport("yolo_cpp_dll.dll")]
        public static extern int detect_image(string filename, ref bbox_t container);

        [DllImport("yolo_cpp_dll.dll")]
        public static extern int dispose();

        public struct bbox_t
        {
            public UInt32 x, y, w, h;    // (x,y) - top-left corner, (w, h) - width & height of bounded box
            public float prob;                 // confidence - probability that the object was found correctly
            public UInt32 obj_id;        // class of object - from range [0, classes-1]
            public UInt32 track_id;      // tracking id for video (0 - untracked, 1 - inf - tracked object)
            public UInt32 frames_counter;
        };

        public YoloWrapper(string configurationFilename, string weightsFilename, int gpu)
        {
            init(configurationFilename, weightsFilename, gpu);
        }

        public void Dispose()
        {
            dispose();
        }

        public bbox_t Detect(string filename)
        {
            var container = new bbox_t();
            detect_image(filename, ref container);
            return container ;
        }
    }

**C++ changes**

yolo_v2_class.hpp (Add this code block)

	extern "C" __declspec(dllexport) int init(const char *configurationFilename, const char *weightsFilename, int gpu);
	extern "C" __declspec(dllexport) int detect_image(const char *filename, bbox_t &data);
	extern "C" __declspec(dllexport) int dispose();

yolo_v2_class.cpp (Add this code block)

	static Detector* detector;

	int init(const char *configurationFilename, const char *weightsFilename, int gpu) {
		std::string configurationFilenameString;
		configurationFilenameString = configurationFilename;
		std::string weightsFilenameString;
		weightsFilenameString = weightsFilename;

		detector = new Detector(configurationFilenameString, weightsFilenameString, gpu);
		return 1;
	}

	int detect_image(const char *filename, bbox_t &container) {
		std::string filenameString;
		filenameString = filename;
		std::vector<bbox_t> detection = detector->detect(filenameString);
		container = detection[0];
		return 1;
	}

	int dispose() {
		detector->~Detector();
		return 1;
	}

**Comment by tinohager** [comment]
@AlexeyAB what you think about this solution? Can you explain that it works that way?

**Comment by AlexeyAB** [comment]
Also if you can work with arrays and C pointers, you can try to pass C pointer to the array of `bbox_t`
```cpp
int detect_image(const char *filename, bbox_t *container) {
	std::string filenameString;
	filenameString = filename;
	std::vector<bbox_t> detection = detector->detect(filenameString);
	for(size_t i = 0; i < detection.size(); ++i)
		container[i] = detection[i];
	return 1;
}
```

`extern "C" __declspec(dllexport) int detect_image(const char *filename, bbox_t *data);`

in C#
```c#
    public bbox_t* Detect(string filename)
    {
        //var container = new bbox_t();
        fixed (bbox_t* container= new bbox_t[1000])
        detect_image(filename, container);
        return container ;
    }

```

**Comment by tinohager** [comment]
With maximum 10 results

**C# YoloWrapper**

    public class YoloWrapper : IDisposable
    {
        [DllImport("yolo_cpp_dll.dll")]
        public static extern int init(string configurationFilename, string weightsFilename, int gpu);

        [DllImport("yolo_cpp_dll.dll")]
        public static extern int detect_image(string filename, ref BboxContainer container);

        [DllImport("yolo_cpp_dll.dll")]
        public static extern int dispose();

        public struct bbox_t
        {
            public UInt32 x, y, w, h;    // (x,y) - top-left corner, (w, h) - width & height of bounded box
            public float prob;                 // confidence - probability that the object was found correctly
            public UInt32 obj_id;        // class of object - from range [0, classes-1]
            public UInt32 track_id;      // tracking id for video (0 - untracked, 1 - inf - tracked object)
            public UInt32 frames_counter;
        };

        [StructLayout(LayoutKind.Sequential, Size = 10)]
        public struct BboxContainer
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 10)]
            public bbox_t[] candidates;
        }

        public YoloWrapper(string configurationFilename, string weightsFilename, int gpu)
        {
            init(configurationFilename, weightsFilename, gpu);
        }

        public void Dispose()
        {
            dispose();
        }

        public bbox_t[] Detect(string filename)
        {
            BboxContainer container = new BboxContainer();
            var count = detect_image(filename, ref container);

            return container.candidates;
        }
    }

**C++ changes**

yolo_v2_class.hpp (Add this code block)

	struct bbox_t_container {
		bbox_t candidates[10];
	};

	extern "C" __declspec(dllexport) int init(const char *configurationFilename, const char *weightsFilename, int gpu);
	extern "C" __declspec(dllexport) int detect_image(const char *filename, bbox_t_container &container);
	extern "C" __declspec(dllexport) int dispose();

yolo_v2_class.cpp (Add this code block)

	static Detector* detector;

	int init(const char *configurationFilename, const char *weightsFilename, int gpu) {
		std::string configurationFilenameString;
		configurationFilenameString = configurationFilename;
		std::string weightsFilenameString;
		weightsFilenameString = weightsFilename;

		detector = new Detector(configurationFilenameString, weightsFilenameString, gpu);
		return 1;
	}

	int detect_image(const char *filename, bbox_t_container &container) {
		std::string filenameString;
		filenameString = filename;
		std::vector<bbox_t> detection = detector->detect(filenameString);
		for (size_t i = 0; i < detection.size(); ++i)
			container.candidates[i] = detection[i];
		return detection.size();
	}

	int dispose() {
		detector->~Detector();
		return 1;
	}

**Comment by tinohager** [comment]
@AlexeyAB Can we add the changes to your project?

**Comment by AlexeyAB** [comment]
@tinohager Yes, just let we do some changes:

* use smart-pointer `unique_ptr<Detector>` instead of raw-pointer `Detector *`
* use max 1000 objects, it will use only 32 000 bytes.
* use single point of changing for max objects, for example `#define C_SHARP_MAX_OBJECTS 1000`, and then `for (size_t i = 0; i < detection.size() && i < C_SHARP_MAX_OBJECTS; ++i)` to avoid access violation (seg-fault) error
* use ` int max_objects();` to get max_objects in the C# code, something like this `[StructLayout(LayoutKind.Sequential, Size = max_objects())]`, I don't know C#

* also try to add function `detect_image()` that can get 
    * `cv::Mat` (**OpenCV**) 
    * or/and `image_t`(**Darknet**) 
    * or/and `Image<Bgr, Byte>` that is got from `capture.QueryFrame();`(**EmguCV**)

* then check that all other things work well, then or make a pull-request, or I can add this code by myself

C# YoloWrapper

```c#
public class YoloWrapper : IDisposable
{
	[DllImport("yolo_cpp_dll.dll")]
	public static extern int init(string configurationFilename, string weightsFilename, int gpu);

	[DllImport("yolo_cpp_dll.dll")]
	public static extern int detect_image(string filename, ref BboxContainer container);

	[DllImport("yolo_cpp_dll.dll")]
	public static extern int dispose();

	public struct bbox_t
	{
		public UInt32 x, y, w, h;    // (x,y) - top-left corner, (w, h) - width & height of bounded box
		public float prob;                 // confidence - probability that the object was found correctly
		public UInt32 obj_id;        // class of object - from range [0, classes-1]
		public UInt32 track_id;      // tracking id for video (0 - untracked, 1 - inf - tracked object)
		public UInt32 frames_counter;
	};

	[StructLayout(LayoutKind.Sequential, Size = 1000)]
	public struct BboxContainer
	{
		[MarshalAs(UnmanagedType.ByValArray, SizeConst = 1000)]
		public bbox_t[] candidates;
	}

	public YoloWrapper(string configurationFilename, string weightsFilename, int gpu)
	{
		init(configurationFilename, weightsFilename, gpu);
	}

	public void Dispose()
	{
		dispose();
	}

	public bbox_t[] Detect(string filename)
	{
		BboxContainer container = new BboxContainer();
		var count = detect_image(filename, ref container);

		return container.candidates;
	}
}
```


C++ changes

yolo_v2_class.hpp (Add this code block)
```cpp
#define C_SHARP_MAX_OBJECTS 1000
struct bbox_t_container {
	bbox_t candidates[C_SHARP_MAX_OBJECTS];
};

extern "C" __declspec(dllexport) int max_objects();
extern "C" __declspec(dllexport) int init(const char *configurationFilename, const char *weightsFilename, int gpu);
extern "C" __declspec(dllexport) int detect_image(const char *filename, bbox_t_container &container);
extern "C" __declspec(dllexport) int dispose();
```

yolo_v2_class.cpp (Add this code block)
```cpp
int max_objects() { return C_SHARP_MAX_OBJECTS; }

static std::unique_ptr<Detector> detector;

int init(const char *configurationFilename, const char *weightsFilename, int gpu) {
	std::string configurationFilenameString;
	configurationFilenameString = configurationFilename;
	std::string weightsFilenameString;
	weightsFilenameString = weightsFilename;

	detector(new Detector(configurationFilenameString, weightsFilenameString, gpu));
	return 1;
}

int detect_image(const char *filename, bbox_t_container &container) {
	std::string filenameString;
	filenameString = filename;
	std::vector<bbox_t> detection = detector->detect(filenameString);
	for (size_t i = 0; i < detection.size() && i < C_SHARP_MAX_OBJECTS; ++i)
		container.candidates[i] = detection[i];
	return detection.size();
}

int dispose() {
	detector.reset();
	return 1;
}
```

**Comment by tinohager** [comment]
@AlexeyAB Okay i check this soon as possible

**Comment by AlexeyAB** [comment]
> **detect_image with cv::Mat**
> 
> I have add a second method for detect_image with cv::Mat but if i activate opencv i have some errors (opencv340)
> ![2018-06-23 10_17_26-yolo_cpp_dll_no_gpu - microsoft visual studio](https://user-images.githubusercontent.com/8215186/41807380-b96b0d9e-76ce-11e8-87ad-2baa9f724fe6.png)

I fixed `yolo_cpp_dll_no_gpu.vcxproj`, try to compile it now.
Also I commented your pull requrest.

**Comment by alpexjava** [comment]
Hi there.
1. You have dll not found because you didn't copy all necessary staff to your debug/release executable location.
It looks you missed 2 ffmpeg DLLs and (!!) and pthreadVC2.dll(!!). To check what exactly the compiled Y3 DLLs need - just try to move your results to compiled original Darknet .....x64/ folder and your DLL wil be loaded as expected.
2. I tried standard format for jpg/png:

`           
 BitmapData bData = bmp.LockBits(new Rectangle(0, 0, bmp.Width, bmp.Height), ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb);

 //.Format32bppArgb  should match to cv::Mat(width, height, CV_8UC4, imgData), i guess. Or ....?

            IntPtr sourcePoint = bData.Scan0;

            // Declare an array to hold the bytes of the bitmap.
            int byteLength = Math.Abs(bData.Stride) * bmp.Height;

// and then 2 versions
// 1: C#
detect_mat1(const uint8_t* data, const size_t data_length, bbox_t_container &container)
//C++ : 
//std::vector<char> vdata(data, data + data_length);
//cv::Mat image = imdecode(cv::Mat(vdata), 1);

//2: C#
detect_mat2((uint)bmp.Width, (uint)bmp.Height, sourcePoint, byteLength, 0.2f, out container_result);
//C++: 	std::vector<char> vdata(data, data + data_length);
//	       cv::Mat image = cv::Mat(width, height, CV_8UC4, imgData);
`
Config: Linker and C/C++ fortified with ref to: 
C:\OpenCV34\opencv\build\x64\vc14\lib;
and
C:\OpenCV34\opencv\build\include;
DUMPBIN shows all guys in place:
13    C 000406B0 detect_image = detect_image
         14    D 000407C0 detect_mat = detect_mat
         15    E 000407D0 dispose = dispose
. . . . . .
         25   18 00040570 init = init
All compiled Darknet projects run well in the same environment: Cuda, cudnn, GTX-960(4Mb) OpenCV340, Win10 VS2017
3.  PLaying a lot with recently provided changes i have always the candidates[1000]  array populated with blank items (see screen shots).
![eaxchtemempty](https://user-images.githubusercontent.com/3071250/41817739-2f35eb64-77e4-11e8-9a32-421e8d04cfd9.jpg)

AlexeyAB, please look into this part. We need your help for the C# <----> C++ communication part.
Thanks.

Regards,
Alexei P.

**Comment by AlexeyAB** [comment]
@alpexjava Use the new C# wrapper: https://github.com/AlexeyAB/darknet/blob/master/build/darknet/YoloWrapper.cs

**Comment by alpexjava** [comment]
Hi AlexeyAB.
I still have empty candidates as yesterday. The possible reason is missed/disappeared method(s), i guess.
Could you, please, fix/restore missed method:
`std::vector<bbox_t> detect(cv::Mat mat, float thresh = 0.2, bool use_mean = false)`?

![detect_mat_tresh_mean_methodmissed](https://user-images.githubusercontent.com/3071250/41859241-1c01ed4e-78df-11e8-9c85-221979b7fccc.jpg)

Or restore image_t mat_to_image_t(Mat m) ?

**Comment by AlexeyAB** [comment]
@alpexjava 

> Could you, please, fix/restore missed method:
> std::vector<bbox_t> detect(cv::Mat mat, float thresh = 0.2, bool use_mean = false)?

Still there is this method: https://github.com/AlexeyAB/darknet/blob/24c889d85705643ca4860dea88827a7f1893b731/src/yolo_v2_class.hpp#L87

Just open `\yolo_cpp_dll.sln` in MSVS -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and add: `OPENCV;`
And compile it.

**Comment by alpexjava** [comment]
Thx. Obviously it was compiled many times. 👍 
Otherwise i wouldn't have well tested detect_image(const char *filename, bbox_t_container &container) as i mentioned.
I did some simple tests one by one and together:
```
int detect_mat(const uint8_t* data, const size_t data_length, bbox_t_container &container) {
	container.candidates[0].h = 111; // !!!!!!!!!!!!!!
#ifdef OPENCV
	container.candidates[1].h = 333;  // !!!!!!!!!!!!!!
	//return 1;
    std::vector<char> vdata(data, data + data_length);
    cv::Mat image = imdecode(cv::Mat(vdata), 1);
	
    std::vector<bbox_t> detection = detector->detect(image, 0.2f, false);
    for (size_t i = 0; i < detection.size() && i < C_SHARP_MAX_OBJECTS; ++i)
        container.candidates[i] = detection[i];

	container.candidates[2].h = 555;  // !!!!!!!!!!!!!!
    return detection.size();
#else
    return -1;
#endif	// OPENCV
```
and received:
 container.candidates[0].h = 111
container.candidates[1].h = 0
container.candidates[2].h = 0
That is why i thought something wrong with the method. Comparing with 
`detect(std::string image_filename, float thresh = 0.2, bool use_mean = false);`
the `int detect_mat(const uint8_t* data, const size_t data_length, bbox_t_container &container) `
arranged in a different way.
What do you think, please ?

**Comment by alpexjava** [comment]
Are you sure that
```
#ifdef OPENCV
#include <opencv2/opencv.hpp>			// C++
#include "opencv2/highgui/highgui_c.h"	// C
#include "opencv2/imgproc/imgproc_c.h"	// C
#endif	// OPENCV
```
is NOT missed in yolo__v2_class.cpp and "lives" in hpp?

**Comment by AlexeyAB** [comment]
@alpexjava 

> Are you sure that
> ```
> #ifdef OPENCV
> #include <opencv2/opencv.hpp>			// C++
> #include "opencv2/highgui/highgui_c.h"	// C
> #include "opencv2/imgproc/imgproc_c.h"	// C
> #endif	// OPENCV
> ```
> is NOT missed in yolo__v2_class.cpp and "lives" in hpp?


* What do you mean? How can it be missed if it is here? ) 
https://github.com/AlexeyAB/darknet/blob/24c889d85705643ca4860dea88827a7f1893b731/src/yolo_v2_class.hpp#L42-L46
And `yolo_v2_class.hpp` is included at the top of `yolo_v2_class.cpp`: https://github.com/AlexeyAB/darknet/blob/24c889d85705643ca4860dea88827a7f1893b731/src/yolo_v2_class.cpp#L1

* What is the "lives"?

* Did you do this? Just open `\yolo_cpp_dll.sln` in MSVS -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and add: `OPENCV;`

**Comment by alpexjava** [comment]
**Yep !!** Now it works as expected. 
Thank you AlexeyAB and tinohager.
Yes, i missed OPENCV to add to Preprocessor Def. (I didn't want to include OpenCV in Path).

What was it ? -Missed OpenCV and I guess, i was confused by minor wrong title. Actually i was talking about yolo_cpp_dll_no_gpu. In recently built masters you provided Target Name: "**yolo_cpp_dll**" for the **yolo_cpp_dll_no_gpu**. I just downloaded your last version and changed it to **"$(ProjectName)"**. It allowed me to fix the mess i had. Thank you again for such effective and fast response / support and patience.

Cheers
Алексей П.

**Comment by wouterbac1** [comment]
Hi, I have been trying to implement the YoloWrapper in my application. The two calls supported are 

1. "detect_image", which uses a filename from an image saved on a disk. This option works fine, but my application involes a camera that save a Bitmap into memory. Saving to disk is not an option since this delays the application.

2. "detect_mat" requires a byte array that is converted into a cv:Mat object. I got this to work using the Windows MemoryStream which converts the bitmap into a byte array. See code:
            using (var ms = new MemoryStream())
            {
                imageIn.Save(ms, System.Drawing.Imaging.ImageFormat.Bmp);

                return ms.ToArray();
            }
This takes about 150ms, mainly due to .Save(). This is too slow for my application. 

Therefore I explored Marshal.Copy() to generate a byte array from a bitmap, this takes only 5 ms. However, this byte array is rejected by the Yolo library, regardless of whether I use a Format24bppArgb or Format32bppArgb as input Bitmap. Both result in an exception: "external component has thrown an exception". Any idea how this is caused? The MemoryStream byte array consists of 2944998 elements, wheras the Marshal byte array consists of 2944944 elements (401*2448*3) in case of 24bpp. It seems that Image.Save() throws away the majority of the 4th image channel, except for 54 elements (2944988-2944944). 

Do  you have any idea why it won't work using Marshal?

Another faster alternative would be to add a third call which has the Bitmap as an argument. This would avoid the byte array conversion altogether. @alpexjava I think you are hinting at this with detect_mat2() right? Do you have any experience implementing this call?


--

**Comment by tinohager** [comment]
@wouterbac1 please create a new issue this one is closed
