### ISSUE TITLE
prediction offset on tiny yolov3

### ISSUE THREAD

**Issue by wanggao1990** [AlexeyAB/darknet#3412]
hi, i have a problem in running windows darknet.exe with tiny yolo v3 model trained on linux gpu darknet (gtx 1080ti, cuda8, cudnn5.1).

The prediction on linux is normal.  But when the model applied in  windows gpu/cpu situation, the prediction has a left-top offset to ground truth bbox.

On the contrary, the windows gpu model predicts a right-bottom offset on linux gpu condition, and predicts normal bbox on linux cpu.

Look forward to your favourable reply.

**Comment by AlexeyAB** [comment]
@wanggao1990 Hi,

* What command do you use for Detection on both Windows and Linux?

* Can you show screenshots on Linux and Windows?

* Do you use exactly this https://github.com/AlexeyAB/darknet repository on both Windows and Linux?

* Do you use the latest version of Darknet in both cases?

* Do you use gtx 1080ti, cuda8, cudnn5.1 on both Windows and Linux?

* Can you share your cfg-file, weights-file and source image (by using google-disk), so I can test it?

**Comment by wanggao1990** [comment]
Sorry for having kept you waiting. 

-  I  built gpu and no_gpu darknet.  The command: 
./darknet(.exe) detect test yolov3_tiny.cfg yolov3_tiny.weights data/dog.jpg -thresh 0.25 (-gpus 0)
- Same gtx 1080ti, cuda8, cudnn5.1 on both Windows and Linux.
- Latest release version from repo https://github.com/AlexeyAB/darknet
- the model, cfg file and img saved in my [github folder](https://github.com/wanggao1990/MarkdownPhotos/tree/master/tmp/1) .
And a comparation of predictions between gpu and cpu model shown in [redictions.pdf](https://github.com/wanggao1990/MarkdownPhotos/blob/master/tmp/1/presictions.pdf) file.

---
By the way, i also test repo https://github.com/pjreddie/darknet and got the same issue.

This week i tested **yolo3**(your repo and pjreddie's repo ) and the predictions is normal.

Today i test your repo https://github.com/AlexeyAB/darknet on linux ( rtx2080ti, cuda 10.1, cudnn7.5 ) and retrained on same dataset. The prediction is totally normal: the model trained on win gpu applied on linux cpu/gpu , and the model trained on linux gpu applied on linux gpu/cpu. (windows: gtx 1080ti, cuda8, cudnn5.1)


For now I roughly think it's due to the cuda and cudnn's version bug.  It embarrassed me. -_-

**Comment by AlexeyAB** [comment]
> For now I roughly think it's due to the cuda and cudnn's version bug. It embarrassed me. -_-

May be yes.

So, did you train the model by using the same dataset (the same labels) and problem is solved?

**Comment by wanggao1990** [comment]
I trained the model by using the same dataset and the same labels, the yolo3-tiny problem is solved .

However, under the same condition and test procedure, I still don't understand that yolo3 results are correct and yolo3-tiny results are abnormal. 

Perhaps the adaptation of darknet to different cuda/cudnn versions has not been fully tested yet.

**Comment by AlexeyAB** [comment]
Such a problem is described here (in issues) for the first time, for any cuda/cudnn versions.
Usually such problems arise due to incorrect labeling of images.
