### ISSUE TITLE
yolo_console_dll, weights model allocate to gpu 0

### ISSUE THREAD

**Issue by manncyam** [AlexeyAB/darknet#468]
Hi Alexey,
I am trying to run multiple instances of yolo_console_dll by modifying line 240 in yolo_consol_dll.cpp to 
Detector detector(cfg_file, weights_file, gpuIdx);
I tried to change gpuIdx to 1 but I saw the weight model is still allocated in gpu 0 memory not gpu 1.
Is it intended to be that way for performance?

**Comment by AlexeyAB** [comment]
@manncyam Hi,

Should be used GPU-1, and the weight model should be allocated in gpu 1 memory.

* Can you update your code from this repo and show console output when you done `Detector detector(cfg_file, weights_file, gpuIdx);`?

* Can you show screenshot of memory occupation before and after `Detector detector(cfg_file, weights_file, gpuIdx);`?

**Comment by manncyam** [comment]
Hi Alexexy,
Here is what I changed in yolo_console_dll.cpp
![image](https://user-images.githubusercontent.com/8252839/37556799-416c381c-29b8-11e8-97cf-8bb231753290.png)

And here is the result when I ran starting by gpu 2 1 and 0. gpu2 and 1 used the same memory but gpu 0 used more memory
![weights](https://user-images.githubusercontent.com/8252839/37556819-775d44c0-29b8-11e8-9b29-75359efe462e.JPG)

And here is the result when I ran starting from gpu 0 1 and 2. 
![image](https://user-images.githubusercontent.com/8252839/37556841-db17d23c-29b8-11e8-826d-c9acd399890a.png)

**Comment by AlexeyAB** [comment]
@manncyam So each time the same amount of memory is allocated
* `7757-6823 = 934` - in most cases
* `7097-6163 = 934` - when GPU-0 is initialized by the last. But in this case - initially free mem = `7097` instead of `7757`, so previous launches for GPU-2 and GPU-1 can occupy memory from GPU-0.

Do you compile with TRACK_OPTFLOW or without TRACK_OPTFLOW? https://github.com/AlexeyAB/darknet/blob/2f52cfeb07e11fce8275496164293cf30b732907/src/yolo_console_dll.cpp#L18

`class Tracker_optflow` uses GPU-0 memory by default, if you did not specify a different GPU-id.

**Comment by manncyam** [comment]
@AlexeyAB 
I compiled it without TRACK_OPTFLOW. If GPU-1 and GPU-2 allocated memory for TRACK_OPTFLOW. Amount of memory used on GPU-1 and GPU-2 should be less than GPU-0 but up to the point memory used for each GPU is 934 Mb.
  

- 7757 - 7097  = 660 so GPU-1 takes 330 Mb and GPU-2 takes 330 Mb and the weights of the model is 194 Mb.

**Comment by AlexeyAB** [comment]
@manncyam If you compiled without TRACK_OPTFLOW (i.e. with commented `//#define TRACK_OPTFLOW `), then `class Tracker_optflow` can't use GPU-0 memory.

Also:

* try to add `getchar();` before `Detector detector(`...
* run 3 instances for GPU-2, 1, 0, and see how much free memory is on each
* then press key for each instances, and see how much free memory is on each - if the memory in each case has decreased by the same amount, then Yolo uses memory only from the specified GPU

----

So probably something else use GPU-0 memory. 
Maybe OpenCV takes GPU-0-memory during initialization. Try to compile without OpenCV, will some GPU-0 memory be used?
    (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions - and remove here `OPENCV;`

----

> I also tried to run with tiny-yolo-voc.weights which is only 60.5 Mb but 330 Mb for each GPU-1 and GPU-2 is allocated on GPU-0.

Yolo allocates memory by default:

* for Weights, Worsapce, and for each layer Inputs/Outputs... . So it's bigger than only Weights-file.
* for Backward (this is a small percentage of all memory consumed, so I did not fix it).
* And for whole Batch size if `batch>1` in cfg, but I fixed it - so now it can be changed: https://github.com/AlexeyAB/darknet/blob/2f52cfeb07e11fce8275496164293cf30b732907/src/yolo_v2_class.cpp#L71

**Comment by manncyam** [comment]
@AlexeyAB 
I added the lighted part in cuda_push_array functionn in cuda.c as below
![image](https://user-images.githubusercontent.com/8252839/37561550-4b67422a-2a0e-11e8-99f3-6017573ce9c3.png)

Here is my result:
![image](https://user-images.githubusercontent.com/8252839/37561545-262e7848-2a0e-11e8-8cc4-cc93562e3e8f.png)

I can see that it always push to GPU-0.

**Comment by manncyam** [comment]
@AlexeyAB 
I ran it without openCV and here is the result:
GPU-0, 1, and 2 started with the same memory 7841 Mb. Then I let GPU 1 and 2 initialized the weight first and finally GPU-0.

- GPU 1 and 2: 7841 - 7395 = 446

- GPU 0:  7841 - 6899 = 942

 

![image](https://user-images.githubusercontent.com/8252839/37561791-0e9c3e34-2a15-11e8-9d47-1ba23a60a3a5.png)

**Comment by AlexeyAB** [comment]
@manncyam Thank, yes I see, somthing goes wrong. I will check it.

**Comment by AlexeyAB** [comment]
@manncyam I fixed it.

**Comment by manncyam** [comment]
@AlexeyAB 
I used the latest version and I got linking error. I tried to #include "cuda.h" but I still get the same error.
I used cuda 8.0. Could it be the problem? 
yolo_v2_class.obj : error LNK2001: unresolved external symbol "void __cdecl cuda_set_device(int)" (?cuda_set_device@@YAXH@Z)

**Comment by AlexeyAB** [comment]
@manncyam You should also update `cuda.h` from the previous commit - just download it: https://raw.githubusercontent.com/AlexeyAB/darknet/ced198e9390195875d743d77eadece99c7fd5b38/src/cuda.h

**Comment by manncyam** [comment]
Now, it allocates on each GPU properly. 
Thank @AlexeyAB .
