### ISSUE TITLE
about network resolution

### ISSUE THREAD

**Issue by anandkoirala** [AlexeyAB/darknet#577]
Hi @AlexeyAB 
thanks for the new release of YOLOv3 which is doing its best trained on my custom dataset- although the train time is longer.
network resolution:
I am training on 512x512 images and do inference on 2048x2048 images by increasing the network resolution to 2048 in cfg file for YOLOv2.. but for YOLOv3 this change in resolution will not fit the model in my GPU memory (16 GB)..
the question is when i use faster-RCNN or SSD i can change the inference time input size 2048 and it does its job of detection without any significant increase in memory consumption....   However, YOLO resizes its network to a new size chewing huge memory. is there any workaround?
regards,
Anand

**Comment by AlexeyAB** [comment]
For faster-RCNN or SSD memory consumption in proportion to the size of the neural network. Just Yolo v3 network larger than SSD or backgend networks of Faster RCNN.

Issue: Yolo by default allocates GPU-memory for Detection and Training even if you want to to Detection only. I will try to fix it.

**Comment by sivagnanamn** [comment]
Just adding my two cents by elaborating @AlexeyAB's answer: 
Darknet framework allocated both CPU & GPU memory for storing the following,

- Weights (used while both training & inference)
- Biases (used while both training & inference)
- Weight updates (used only during training )
- Bias updates (used only during training)
- and mean updates, variance updates (used only during training) etc 

For ex:
https://github.com/AlexeyAB/darknet/blob/be9d971ddb9ea0520da78cfff7788eb5481f095e/src/convolutional_layer.c#L314

Such unused memory allocations (during inference time) can be found in `make_xxx_layer()` functions in all the layers that has learnable parameters.

You can reduce your memory consumption during inference time if such variables are removed (especially from convolution & connected layers).

**Comment by TheExDeus** [comment]
I also found during profiling that memory allocations on the CPU are much slower than the GPU, so even when running on GPU the load time is mostly CPU memallocs. I also think this should be fixed.

**Comment by iraadit** [comment]
@AlexeyAB, did you finally fix it?
Thanks

**Comment by AlexeyAB** [comment]
@TheExDeus No, I didn't fix it.
There is still used memory allocation for backward+update, even when we are using Detection, but there is used `mini_batch=1` (batch=1 subdivisions=1) for Detection regardless of cfg-file.

You can use this repo, if you want to use only Yolo v2/v3 - it allocates memory only for Detection (there isn't training): https://github.com/AlexeyAB/yolo2_light 
For Detection use `./darknet detector test obj.names yolov3.cfg yolov3.weights dog.jpg` or `./darknet detector demo obj.names yolov3.cfg yolov3.weights test.mp4`
