### ISSUE TITLE
darknet_video.py doesn't work

### ISSUE THREAD

**Issue by vykintazo** [AlexeyAB/darknet#6060]
I'm trying to run prediction on video file using [darknet_video.py](https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py). I haven't modified the file except changed the paths to cofig, weights, meta and video file.
The problem is that it seems that OpenCV reads only the first video frame on every `while` loop iteration. I can see the  image displayed with `cv2.imshow()` and it doesn't change, despite output showing that prediction is progressing further.
If I add `cap.write(image)` to the code (as I understood the code doesn't write predicted frames to video by default) I get the video consisting only of the first frame of original video.
I'm using Jupyter Lab and importing required functions there. Image detection with `performDetect()` from darknet.py works fine.
Has anyone any ideas what's happening?

Thanks

**Comment by prospektai** [comment]
I'm having the same issue ://

**Comment by flowzen1337** [comment]
a) can you add print(str(prev_time)) after the line `prev_time = time.time()` in the while loop?

Does it keep printing the time or does it also hang here?

b) One other try is to increase cv2.waitKey(3) to cv2.waitKey(500) (<- that is waiting half a second before running through the next iteration in the loop).

So i know if cv2.waitKey is to low, the computer doesnt come after the loop and before ready rendered the image, the next loop already runs through and tries to render the image and displays it again. So try both, if a) keeps printing timestamps but image still doesnt update, then try b) because a) indicates that b) is the problem maybe :-) Keep me updated please if that helped you! Cheers

**Comment by vykintazo** [comment]
Unfortunately, the issue remains.
Time looks good when printing it and increasing `waitKey()` doesn't help.
I tried removing `imshow()` and `waitKey()` altogether and only `out.write()` to file but as before I only get repeated first frame of the original video.

**Comment by flowzen1337** [comment]
hmm that's strange. That's my simplified while Loop, maybe give it a try, as in "https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py" i can't see that out.write() is used somewhere to save the frame to the avi file...


`    while True:`
`        prev_time = time.time()`
`        ret, frame_read = cap.read()`
`        frame_rgb = cv2.cvtColor(frame_read, cv2.COLOR_BGR2RGB)`
`        frame_resized = cv2.resize(frame_rgb,`
`                                   (darknet.network_width(netMain),`
`                                    darknet.network_height(netMain)),`
`                                   interpolation=cv2.INTER_LINEAR)`
`        darknet.copy_image_from_bytes(darknet_image,frame_resized.tobytes())`
`        detections = darknet.detect_image(netMain, metaMain, darknet_image, thresh=0.25)`
`        image = cvDrawBoxes(detections, frame_resized)`
``
``
`        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)`
``
`        out.write(cv2.resize(image, (darknet.network_width(netMain), `darknet.network_height(netMain))))`
`        print(1/(time.time()-prev_time))`
`        #cv2.imshow('Demo', cv2.resize(image, (640, 480)))`
`        cv2.waitKey(1)`

**Comment by vykintazo** [comment]
Well, still doesn't work for me...
But I've managed to isolate issue a bit more by commenting everything except frame reading and showing and uncommenting line-by-line. This is the modified version of the loop code which still works:
```
    while True:
        ret, frame_read = cap.read()
        frame_rgb = cv2.cvtColor(frame_read, cv2.COLOR_BGR2RGB)
        frame_resized = cv2.resize(frame_rgb, (darknet.network_width(netMain), darknet.network_height(netMain)), interpolation=cv2.INTER_LINEAR)
        darknet.copy_image_from_bytes(darknet_image,frame_resized.tobytes())
#         detections = darknet.detect_image(netMain, metaMain, darknet_image, thresh=0.25)
#         image = cvDrawBoxes(detections, frame_resized)
#         image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#         out.write(cv2.resize(image, (darknet.network_width(netMain), darknet.network_height(netMain))))
        cv2.imshow('Demo', frame_resized)
        cv2.waitKey(1)
```
uncomenting second line (`detections = ...`) raises my issue.

**Comment by arnoldhoward** [comment]
Hi, @vykintazo .
Did you fix the issue ?
If you still suffer from this problem, let me know my solution.
at 56 line in darknet.py, please change the DETECTION class like this. 

class DETECTION(Structure):
    _fields_ = [("bbox", BOX),
                ("classes", c_int),
                ("prob", POINTER(c_float)),
                ("mask", POINTER(c_float)),
                ("objectness", c_float),
                ("sort_class", c_int),
                ("uc", POINTER(c_float)),
                ("points", c_int),
                ("embeddings", POINTER(c_float))]

**Comment by vykintazo** [comment]
Hi,
unfortunately issue still persists and your suggestion doesn't fix it... I made two changes to `DETECTION` class, as per your example: `_fields_` to `fields` and added "embeddings" tuple to the array.
I'm almost sure that the problem is unique to me, but just to be sure, is that file, `darknet_video.py`, actually working for anyone? The fact that it declares `cv2.VideoWriter()` on line 86 but never writes to it makes it look like it's incomplete and might not be working at all. If it is actually working for others, maybe this issue is hardware related. I'm doing everything on a pretty good laptop, but it's still just a laptop with intel core i5.

**Comment by arnoldhoward** [comment]
Oh, . 
Main point is add one element in last of DETECTION class. 
"embeddings"
It will help you.

**Comment by AlexeyAB** [comment]
I just fixed it. Download the latest Darknet version.

**Comment by vykintazo** [comment]
Well, I've just clone the repo, compiled darknet from scratch and absolutely nothing has changed - still the same problem. Frames doesn't change, unless I comment out detection step itself, as described above.
A few more new observations:
 - If detection line is not commented (line 107 in darknet_video.py) as explained [above](https://github.com/AlexeyAB/darknet/issues/6060#issuecomment-648909587) it doesn't matter where I'm showing/writing frame with cv2, it still freezes to the first one, even if i show it before doing detections.
- I printed `cap.get(cv2.CAP_PROP_POS_FRAMES)` which shows current frame, it shows frames changing as it should.

For me it all looks like somewhere starting from `darknet.detect_image()` my frame gets mutated and overwritten with the first frame, but I'm probably wrong. Maybe it's platform related? By scrolling through issues related to darknet_video.py, I've seen it working on Windows. I'm on Ubuntu 20.04
