### ISSUE TITLE
failed on compiling on Windows with CMake

### ISSUE THREAD

**Issue by stevenwong951028** [AlexeyAB/darknet#6527]
upon following the instructions on "How to compile on Windows (using CMake)", I've encountered this error at command `.\vcpkg install darknet[full]:x64-windows` 

![image](https://user-images.githubusercontent.com/39522550/90856330-46d1e280-e3b4-11ea-8d02-36865e6b214f.png)

[config-x64-windows-out.log](https://github.com/AlexeyAB/darknet/files/5107002/config-x64-windows-out.log)

the log file states that 
Configuring incomplete, errors occurred!
See also "D:/gitYolo/vcpkg/buildtrees/opencv4/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "D:/gitYolo/vcpkg/buildtrees/opencv4/x64-windows-rel/CMakeFiles/CMakeError.log".
[CMakeError.log](https://github.com/AlexeyAB/darknet/files/5107010/CMakeError.log)
[CMakeOutput.log](https://github.com/AlexeyAB/darknet/files/5107011/CMakeOutput.log)

the CMakeError states that
CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'D:/gitYolo/vcpkg/installed/x64-windows/include/libpng/png.h': No such file or directory
ninja: build stopped: subcommand failed.

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.

I don't understand the errors though, I just follow the build command as stated on the repository? 
Any help or suggestions is appreciated.

my specs:
VS2019 Community
CUDA 10.2
CuDNN 7.6.5
Cmake 3.18.1
GTX 965M

**Comment by bencost97** [comment]
I'm also getting this issue following this procedure.
My specs:
VS2017 Community
CUDA 10.0
CuDNN 7.6.5
Cmake 3.17.4
GTX 1050ti
[config-x64-windows-out.log](https://github.com/AlexeyAB/darknet/files/5107285/config-x64-windows-out.log)
[CMakeError.log](https://github.com/AlexeyAB/darknet/files/5107277/CMakeError.log)
[CMakeOutput.log](https://github.com/AlexeyAB/darknet/files/5107278/CMakeOutput.log)

**Comment by abdullahcavuss** [comment]
I have same error too :/

**Comment by stevenwong951028** [comment]
quoted from "TheAshwaniKYesterday" from 'darknet/official' discord channel:

> This was due to ffmpeg package i think.. and there was a repo merge pending to fix this.
The fix was merged in vcpkg a two days back.. I think if you clone again and try this will go..

build success after removing and re-cloning file vcpkg

**Comment by JWFrank** [comment]
Hi, @stevenwong951028 
I have an issue about "pthread.h" not found on Windows
Do you solve this issue via re-cloning vcpkg?
I get the latest vcpkg but I still get this error

my environments:
VS2019 Community
CUDA 10.1
CuDNN 7.6.5
NVIDIA 1080

Thanks for your help
