### ISSUE TITLE
Segmentation fault when running darknet.py file for yolov4-tiny model in Jetson Nano

### ISSUE THREAD

**Issue by srikar242** [AlexeyAB/darknet#6711]
Hey @AlexeyAB , I am getting segmentation fault while trying to run yolov4-tiny model in Jetson Nano using darknet.py file. However, the same thing with the same code is working fine on my system. But on nano, I am getting segmentation fault after the model gets loaded in memory. I have attached screenshot below. Any thoughts on this?

![Screenshot from 2020-09-22 17-54-12](https://user-images.githubusercontent.com/61647908/93881607-c24ce980-fcfc-11ea-9877-b46349a5e59c.png)

**Comment by bulatnv88** [comment]
Hello @srikar242, I think segmentation fault is common problem on Jetson Nano. Possibly Jetson is out memory.
Check this forum.
https://forums.developer.nvidia.com/t/run-the-jetson-inference-error-segmentation-fault-core-dumped/75047

Hope it will help you.

**Comment by srikar242** [comment]
Hi @bulatnv88 
Thanks for your reply. Segmentation fault problem on my nano was not due to memory issue. I think there was a small bug in code of this repo and that bug was resolved later on. I downloaded fresh repo and recompiled it again. Now there is no issue in nano. I'm closing this issue now.

**Comment by ItsHelloWod** [comment]
> Hi @bulatnv88
> Thanks for your reply. Segmentation fault problem on my nano was not due to memory issue. I think there was a small bug in code of this repo and that bug was resolved later on. I downloaded fresh repo and recompiled it again. Now there is no issue in nano. I'm closing this issue now.

However, I cloned the newest version it still does not work in nano.
