### ISSUE TITLE
Global Bug related to the new MSVS  on Windows

### ISSUE THREAD

**Issue by AlexeyAB** [AlexeyAB/darknet#7533]
Global **Bug related to the new MSVS** (and CUDA) on Windows, issues: https://github.com/AlexeyAB/darknet/issues/6694#issuecomment-803467320 , #7457, #7498, #7500

`error : calling a host function("__floorf") from a device function`

Issues in other projects:
* FFMPEG: https://trac.ffmpeg.org/ticket/9150
* FuxiCV: https://github.com/FuxiCV/pt_mesh_renderer/issues/4
* https://devtalk.blender.org/t/cuda-compile-error-windows-10/17886
...

@cenit Do you know this is a bug in the new MSVS? It seems that installing an earlier version of the MSVS helps: https://devtalk.blender.org/t/cuda-compile-error-windows-10/17886/4

**Comment by AlexeyAB** [comment]
Possible fix is merged: https://github.com/AlexeyAB/darknet/pull/7515

**Comment by Goru1890** [comment]
I'm still not able to install darknet with vcpkg (vcpkg install darknet[opencv3-cuda,cudnn). 

`error : calling a host function("__floorf") from a device function`

**Comment by sfhacker** [comment]
We have just built darknet master branch from source (Windows 10 x64) with OpenCV 4.5.2 support (no CUDA) and no issues at all.
We will enable CUDA and report here.

![image](https://user-images.githubusercontent.com/25817529/114280060-f0b4cb00-9a7a-11eb-907f-ae92a6350fb6.png)
